"""SFT trainer: LoRA fine-tune google/gemma-4-E4B-it on the menu-extraction corpus.

Consumes `data/sft/<family>/train.jsonl` (produced by scripts/datasets/build_sft.py):
one JSON object per line with a Gemma-format `messages` list (student system prompt,
user, bundled assistant tool-call+tool_response turns, final assistant JSON). The
tools are NOT stored per row -- we import the two tool callables here and pass them
as `tools=` to the chat template so the tool declarations render into the system turn
exactly as at inference.

Design decisions (see notes/runpod_sft.md and CLAUDE.md):
- LoRA (rank ~16-32) on a **bf16** base -- not full-FT, not 4-bit. Target: 2x H200.
- **Action-only** training data (no reasoning) -- handled upstream by build_sft.py.
- **assistant_only_loss fallback.** Gemma 4's chat template has NO `{% generation %}`
  markers, so TRL's `assistant_only_loss` is a silent no-op here (verified: the
  assistant mask comes back all-zero). We instead compute the assistant-token mask
  OURSELVES from the template's prefix-preservation property (see build_labels) and
  feed TRL a **pre-tokenized** dataset (input_ids/attention_mask/labels). TRL skips
  its own tokenization when a dataset already has `input_ids`, so our labels (with
  non-assistant tokens set to -100) are what the loss uses. `assistant_only_loss`
  is therefore left False in the SFTConfig on purpose.
- **Long sequences.** Episodes carry several capped scraped pages. Examples longer
  than --max-length are DROPPED (never right-truncated -- that would cut the final
  JSON target). gradient_checkpointing on; packing off (varlen packing needs
  FlashAttention, which cannot serve this model's head_dim=512 layers).
- **DDP-safe model load.** No `device_map` (breaks accelerate DDP); we reuse
  model.py's GQA/SDPA patch but omit its device_map. Launch under
  `accelerate launch`/`torchrun` (plain python = single process, GPU 2 idle).

On a successful run a `meta.json` lineage record (plan §6) is written next to the
adapter: base + dataset (by md5), the quant recipe, hyperparams, git sha.

Run (2x H200, from repo root, under tmux):
  accelerate launch --config_file configs/accelerate_ddp.yaml \
      scripts/train/train_sft.py --family gemma-4-e4b-it \
      --output-dir /workspace/gemma-menu-sft
  # torchrun equivalent:
  torchrun --nproc_per_node=2 scripts/train/train_sft.py --family gemma-4-e4b-it \
      --output-dir /workspace/gemma-menu-sft

Dev box (1x 24GB, no real training): --dry-run builds the dataset + resolved
config on CPU/tokenizer-only and prints one rendered+masked example, WITHOUT
loading the model or calling .train().
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# Shared modules live in src/; the gemma loader (model.py) in src/gemma/. Put both
# on the path so the flat imports below resolve when this is run as a script.
# scripts/train/ is one level deeper than v1's scripts/, so parents[2] is the repo root.
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "src" / "gemma"))

from run_meta import md5_file, write_run_meta  # noqa: E402

# Keep HF tokenizers quiet under the (potential) fork in dataset prep.
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

# Default student family (selects the per-family SFT export + models/<family>/ layout).
DEFAULT_FAMILY = "gemma-4-e4b-it"

# ID of the single token the template emits to OPEN a tool_response block
# (`<|tool_response>`). It trails an assistant tool-call render but is produced by
# the environment, not the model (which stops at `<tool_call|>`), so build_labels
# trims it off the trained span. Resolved from the live tokenizer at runtime;
# this constant is only the fallback / documentation.
TOOL_RESPONSE_OPEN = "<|tool_response>"


# ---------------------------------------------------------------------------
# Pure helpers (unit-tested in tests/test_train_sft.py -- no GPU/model needed)
# ---------------------------------------------------------------------------
def effective_batch_size(per_device: int, grad_accum: int, num_processes: int) -> int:
    """Effective (global) batch = per_device x grad_accum x num_processes(GPUs)."""
    return per_device * grad_accum * num_processes


def trim_open_call_end(input_ids: list[int], end: int, tool_response_open_id: int) -> int:
    """Drop a trailing `<|tool_response>` opener from a tool-call span.

    An assistant message with tool_calls but no tool_responses renders as
    `...<tool_call|><|tool_response>` -- the template opens the response block for
    the (still absent) tool result. That opener token is emitted by the
    environment, not generated by the model (which stops at `<tool_call|>`), so it
    must not carry loss. `end` is the exclusive end index into `input_ids`; if the
    last token in the span is the opener, back it up by one.
    """
    if end > 0 and input_ids[end - 1] == tool_response_open_id:
        return end - 1
    return end


def partition_by_length(lengths: list[int], max_length: int) -> tuple[list[int], list[int]]:
    """Split example indices into (kept, dropped) by token length.

    Examples with length > max_length are DROPPED (not truncated) so the final
    JSON target is never clipped. length == 0 (a render failure sentinel) is also
    dropped. Returns (kept_indices, dropped_indices).
    """
    kept, dropped = [], []
    for i, n in enumerate(lengths):
        if 0 < n <= max_length:
            kept.append(i)
        else:
            dropped.append(i)
    return kept, dropped


def percentiles(values: list[int], ps=(50, 90, 95, 99, 100)) -> dict[int, int]:
    """Nearest-rank percentiles of a list of ints (empty -> zeros)."""
    if not values:
        return {p: 0 for p in ps}
    s = sorted(values)
    out = {}
    for p in ps:
        k = max(0, min(len(s) - 1, round(p / 100 * (len(s) - 1))))
        out[p] = s[k]
    return out


# ---------------------------------------------------------------------------
# Tokenization + assistant-only masking (needs the tokenizer + tool callables)
# ---------------------------------------------------------------------------
def _render_ids(tokenizer, tools, msgs: list[dict], add_gen: bool) -> list[int]:
    enc = tokenizer.apply_chat_template(
        msgs, tools=tools, add_generation_prompt=add_gen, tokenize=True, return_dict=True
    )
    return list(enc["input_ids"])


def build_labels(tokenizer, tools, messages: list[dict], tool_response_open_id: int,
                 assistant_only: bool = True) -> tuple[list[int], list[int]] | None:
    """Render `messages` and build the label mask.

    Returns (input_ids, labels). With assistant_only=True, only the tokens the
    MODEL generates -- each assistant tool-call emission and the final JSON answer
    -- carry loss; everything else (system, user, tool declarations, and the
    scraped tool_response bodies) is set to -100.

    How the mask is derived, given Gemma 4's template has no `{% generation %}`
    markers: the template is prefix-preserving for these single-task trajectories
    (CLAUDE.md), so for the assistant turn at index i the model's generated span is
    exactly [ len(render(messages[:i], add_gen=True)),  <end> ), where <end> is
      - for a tool-call turn: len(render(messages[:i] + [open tool_call], add_gen=False)),
        minus the trailing `<|tool_response>` opener the environment adds; or
      - for the final content turn: len(render(messages[:i+1], add_gen=False)),
        which includes the closing `<turn|>` so the model learns to stop.
    Each sub-render is asserted to be a genuine token-prefix of the full render; if
    that ever fails (a template change / an unexpected message shape) we return
    None so the caller DROPS the example rather than train on a wrong mask.
    """
    full_ids = _render_ids(tokenizer, tools, messages, add_gen=False)
    if assistant_only:
        labels = [-100] * len(full_ids)
    else:
        labels = list(full_ids)

    for i, msg in enumerate(messages):
        if msg.get("role") != "assistant":
            continue
        pre = _render_ids(tokenizer, tools, messages[:i], add_gen=True)
        if pre != full_ids[: len(pre)]:
            return None  # prefix broke -> unsafe to mask; drop
        start = len(pre)

        if msg.get("tool_calls"):
            open_msg = {"role": "assistant", "tool_calls": msg["tool_calls"]}
            end_ids = _render_ids(tokenizer, tools, messages[:i] + [open_msg], add_gen=False)
            if end_ids != full_ids[: len(end_ids)]:
                return None
            end = trim_open_call_end(full_ids, len(end_ids), tool_response_open_id)
        else:
            end_ids = _render_ids(tokenizer, tools, messages[: i + 1], add_gen=False)
            if end_ids != full_ids[: len(end_ids)]:
                return None
            end = len(end_ids)

        if assistant_only:
            for t in range(start, min(end, len(full_ids))):
                labels[t] = full_ids[t]

    return full_ids, labels


# ---------------------------------------------------------------------------
# Dataset construction
# ---------------------------------------------------------------------------
def load_rows(path: str) -> list[dict]:
    rows = []
    # build_sft.py writes UTF-8; read it as UTF-8 explicitly so a non-UTF-8
    # platform locale (e.g. Windows cp1252) can't mis-decode accented names.
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def build_dataset(rows, tokenizer, tools, max_length: int, assistant_only: bool):
    """Tokenize + mask every row, drop over-length/failed ones, return a HF Dataset.

    Returns (dataset, stats) where stats has example/drop counts and the length
    distribution. The dataset has exactly input_ids / attention_mask / labels.
    """
    from datasets import Dataset

    tr_open = tokenizer.convert_tokens_to_ids(TOOL_RESPONSE_OPEN)

    input_ids_all, labels_all, lengths_all = [], [], []
    render_errors = 0
    n = len(rows)
    for idx, row in enumerate(rows):
        if (idx + 1) % 100 == 0:
            print(f"  tokenizing {idx + 1}/{n} ...", flush=True)
        built = build_labels(tokenizer, tools, row["messages"], tr_open, assistant_only)
        if built is None:
            render_errors += 1
            input_ids_all.append([])
            labels_all.append([])
            lengths_all.append(0)
            continue
        ids, labels = built
        input_ids_all.append(ids)
        labels_all.append(labels)
        lengths_all.append(len(ids))

    kept, dropped = partition_by_length(lengths_all, max_length)
    dropped_len = sum(1 for i in dropped if lengths_all[i] > 0)

    ds = Dataset.from_dict({
        "input_ids": [input_ids_all[i] for i in kept],
        "attention_mask": [[1] * lengths_all[i] for i in kept],
        "labels": [labels_all[i] for i in kept],
    })

    kept_lengths = [lengths_all[i] for i in kept]
    stats = {
        "total": n,
        "render_errors": render_errors,
        "dropped_len": dropped_len,
        "kept": len(kept),
        "pct": percentiles([n for n in lengths_all if n > 0]),
        "pct_kept": percentiles(kept_lengths),
        "max_length": max_length,
    }
    return ds, stats


def print_dataset_stats(stats: dict) -> None:
    p = stats["pct"]
    print("\n=== dataset / token-length distribution (build_sft.py output) ===")
    print(f"  rows read:        {stats['total']}")
    print(f"  render errors:    {stats['render_errors']} (dropped -- prefix/mask unsafe)")
    print(f"  dropped >max_len: {stats['dropped_len']} (max_length={stats['max_length']})")
    print(f"  KEPT:             {stats['kept']}")
    print(f"  length p50/p90/p95/p99/max (all rows): "
          f"{p[50]}/{p[90]}/{p[95]}/{p[99]}/{p[100]}")
    frac_dropped = (stats["dropped_len"] / stats["total"]) if stats["total"] else 0.0
    if frac_dropped > 0.10:
        print(f"  [WARN] {frac_dropped:.0%} of examples dropped for length. Consider a "
              f"lower MAX_TOOL_CHARS in build_sft.py, or raise --max-length "
              f"(p95 is {p[95]}).")


# ---------------------------------------------------------------------------
# Model loading (DDP-safe -- NO device_map; reuse model.py's GQA/SDPA patch)
# ---------------------------------------------------------------------------
def load_base_model(attn: str = "sdpa"):
    """Load the bf16 base for training. No device_map (accelerate places it)."""
    import torch
    from transformers import AutoModelForCausalLM
    # model.py owns the SDPA GQA fix (forces repeat_kv so the mem-efficient kernel
    # serves Gemma 4's head_dim=512 layers instead of OOMing on MATH). Reuse it;
    # do NOT reuse its load_model (that pins device_map={"":0}, which breaks DDP).
    from model import MODEL_ID, _force_repeat_kv_for_efficient_sdpa

    if attn == "sdpa":
        _force_repeat_kv_for_efficient_sdpa()

    print(f"Loading {MODEL_ID} (bf16, attn={attn}, no device_map) ...", flush=True)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID, dtype=torch.bfloat16, attn_implementation=attn
    )
    model.config.use_cache = False  # required with gradient_checkpointing
    return model


# ---------------------------------------------------------------------------
# Collator: pad a pre-tokenized batch (input_ids/attention_mask/labels)
# ---------------------------------------------------------------------------
class PadCollator:
    """Right-pad pre-tokenized examples; pad labels with -100 so they carry no loss."""

    def __init__(self, pad_token_id: int):
        self.pad_token_id = pad_token_id

    def __call__(self, features):
        import torch
        maxlen = max(len(f["input_ids"]) for f in features)
        batch = {"input_ids": [], "attention_mask": [], "labels": []}
        for f in features:
            ids, am, lab = f["input_ids"], f["attention_mask"], f["labels"]
            pad = maxlen - len(ids)
            batch["input_ids"].append(ids + [self.pad_token_id] * pad)
            batch["attention_mask"].append(am + [0] * pad)
            batch["labels"].append(lab + [-100] * pad)
        return {k: torch.tensor(v, dtype=torch.long) for k, v in batch.items()}


# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--family", default=DEFAULT_FAMILY,
                   help=f"student family key; selects data/sft/<family>/train.jsonl and the "
                        f"models/<family>/ layout recorded in meta.json (default {DEFAULT_FAMILY})")
    p.add_argument("--data", default=None,
                   help="SFT jsonl (scripts/datasets/build_sft.py output); "
                        "default data/sft/<family>/train.jsonl")
    p.add_argument("--output-dir", default="/workspace/gemma-menu-sft",
                   help="persistent (RunPod network volume) dir for adapter + merged checkpoint + meta.json")
    p.add_argument("--run-id", default=None,
                   help="lineage run id recorded in meta.json (default: the --output-dir "
                        "basename). Use the models/<family>/sft/<run-id>/ convention, e.g. "
                        "20260714-qlora-r16.")
    # sequence / masking
    p.add_argument("--max-length", type=int, default=32768,
                   help="drop (don't truncate) examples longer than this. Grounded in the "
                        "real train.jsonl distribution (p50~14k, p95~95k tokens at "
                        "MAX_TOOL_CHARS=75000): 32768 keeps ~80%%. Covering p95 would need "
                        "~98k tokens, whose LM-head logits risk OOM even on H200 -- the "
                        "better lever for the long tail is a lower MAX_TOOL_CHARS in "
                        "build_sft.py. Raise only if you've verified memory headroom.")
    p.add_argument("--no-assistant-only-loss", action="store_true",
                   help="train on the full sequence instead of masking to assistant tokens "
                        "(default: assistant-only via our fallback mask)")
    # LoRA
    p.add_argument("--lora-r", type=int, default=16)
    p.add_argument("--lora-alpha", type=int, default=32)
    p.add_argument("--lora-dropout", type=float, default=0.05)
    p.add_argument("--lora-target-modules", nargs="+",
                   default=["q_proj", "k_proj", "v_proj", "o_proj",
                            "gate_proj", "up_proj", "down_proj"])
    # optimization
    p.add_argument("--learning-rate", type=float, default=2e-4)
    p.add_argument("--num-train-epochs", type=float, default=3.0)
    p.add_argument("--per-device-train-batch-size", type=int, default=1)
    p.add_argument("--gradient-accumulation-steps", type=int, default=8)
    p.add_argument("--warmup-ratio", type=float, default=0.03)
    p.add_argument("--lr-scheduler-type", default="cosine")
    p.add_argument("--logging-steps", type=int, default=10)
    p.add_argument("--save-strategy", default="epoch")
    p.add_argument("--attn", default="sdpa", choices=["sdpa", "eager"])
    p.add_argument("--report-to", default="none")
    p.add_argument("--dataset-num-proc", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    # eval
    p.add_argument("--eval-frac", type=float, default=0.0,
                   help="fraction of examples held out as an SFT-loss eval set (0 = none)")
    # meta
    p.add_argument("--num-processes", type=int, default=2,
                   help="GPUs, for the printed effective-batch math (WORLD_SIZE overrides)")
    p.add_argument("--dry-run", action="store_true",
                   help="build dataset + config on CPU/tokenizer-only and print one "
                        "rendered+masked example; do NOT load the model or train")
    return p


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    args = build_arg_parser().parse_args()
    assistant_only = not args.no_assistant_only_loss
    num_processes = int(os.environ.get("WORLD_SIZE", args.num_processes))
    # Per-family SFT export (v2 layout): data/sft/<family>/train.jsonl unless --data
    # overrides it explicitly.
    data_path = args.data or str(ROOT / "data" / "sft" / args.family / "train.jsonl")

    eff_batch = effective_batch_size(
        args.per_device_train_batch_size, args.gradient_accumulation_steps, num_processes)

    from transformers import AutoTokenizer
    from model import MODEL_ID
    from tools import build_model_tools

    print(f"Tokenizer: {MODEL_ID}")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    # The two model-facing tool callables (fixed vendor-neutral docstrings). Backends
    # are dummies -- we only need the DECLARATIONS to render into the system turn,
    # exactly as at inference. Same construction agent.py's __main__ uses.
    tools, _ = build_model_tools(lambda query: "", lambda url, mode="direct": "")

    rows = load_rows(data_path)
    print(f"Loaded {len(rows)} rows from {data_path}")
    ds, stats = build_dataset(rows, tokenizer, tools, args.max_length, assistant_only)
    print_dataset_stats(stats)

    # Optional held-out SFT-loss eval split.
    eval_ds = None
    train_ds = ds
    if args.eval_frac > 0 and len(ds) > 1:
        split = ds.train_test_split(test_size=args.eval_frac, seed=args.seed)
        train_ds, eval_ds = split["train"], split["test"]
        print(f"Eval split: {len(train_ds)} train / {len(eval_ds)} eval")

    print("\n=== resolved config ===")
    print(f"  base model:            {MODEL_ID} (bf16, attn={args.attn})")
    _aol = ("via custom prefix-preservation mask -- Gemma 4 template has no "
            "{% generation %} markers, so TRL's own flag is a silent no-op"
            if assistant_only else "OFF -- training on the full sequence")
    print(f"  assistant_only_loss:   {assistant_only} ({_aol})")
    print(f"  LoRA:                  r={args.lora_r} alpha={args.lora_alpha} "
          f"dropout={args.lora_dropout} targets={args.lora_target_modules}")
    print(f"  max_length:            {args.max_length} (over-length examples DROPPED)")
    print(f"  packing:               False (varlen packing needs FlashAttention -> unavailable)")
    print(f"  gradient_checkpointing:True (use_reentrant=False)")
    print(f"  lr / epochs:           {args.learning_rate} / {args.num_train_epochs}")
    print(f"  per_device_bs x accum x GPUs = effective batch: "
          f"{args.per_device_train_batch_size} x {args.gradient_accumulation_steps} x "
          f"{num_processes} = {eff_batch}")
    print(f"  output-dir:            {args.output_dir}")

    if args.dry_run:
        _print_masked_example(tokenizer, train_ds)
        print("\n[dry-run] built dataset + config only; not loading the model or training.")
        return

    # ---- real training ----
    import torch  # noqa: F401
    from peft import LoraConfig
    from trl import SFTConfig, SFTTrainer

    sft_config = SFTConfig(
        output_dir=args.output_dir,
        per_device_train_batch_size=args.per_device_train_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        warmup_ratio=args.warmup_ratio,
        lr_scheduler_type=args.lr_scheduler_type,
        logging_steps=args.logging_steps,
        save_strategy=args.save_strategy,
        bf16=True,
        tf32=True,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        ddp_find_unused_parameters=False,
        max_length=args.max_length,          # informational: pre-tokenized -> TRL won't retruncate
        packing=False,
        assistant_only_loss=False,           # we mask ourselves (see module docstring)
        dataset_num_proc=args.dataset_num_proc,
        report_to=args.report_to,
        seed=args.seed,
        remove_unused_columns=False,
        eval_strategy="epoch" if eval_ds is not None else "no",
        # Eval memory: the loss logits are seq_len x vocab(262k) x 4B. At the default eval
        # batch of 8 that term is ~8x a training micro-batch and OOMs at 32k (one sequence
        # already fills the card). Evaluate one sequence at a time, loss-only, so eval never
        # materializes more than a single training step's worth of logits.
        per_device_eval_batch_size=args.per_device_train_batch_size,
        prediction_loss_only=True,
    )

    # Gemma 4 E4B is multimodal: the same projection names (q_proj/.../down_proj) also live in the
    # vision_tower and audio_tower, where they are wrapped in Gemma4ClippableLinear -- a type PEFT's
    # LoRA cannot adapt (it only supports bare nn.Linear et al.). A bare-suffix target_modules list
    # matches those towers too and raises "Target module ... is not supported". The language model's
    # own projections are plain nn.Linear, so scope LoRA to them with a regex: PEFT treats a *string*
    # target_modules as a full-match regex (a list is bare-suffix matched and can't express the scope).
    _names = "|".join(re.escape(t) for t in args.lora_target_modules)
    lora_target = rf".*language_model\..*\.({_names})$"

    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=lora_target,
        bias="none",
        task_type="CAUSAL_LM",
    )

    model = load_base_model(attn=args.attn)
    collator = PadCollator(pad_token_id=tokenizer.pad_token_id
                           if tokenizer.pad_token_id is not None else tokenizer.eos_token_id)

    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        processing_class=tokenizer,
        data_collator=collator,
        peft_config=lora_config,
    )
    trainer.train()

    _save_outputs(trainer, tokenizer, args.output_dir, args.attn)

    # Lineage record next to the adapter (plan §6): base + dataset (by md5), the quant
    # recipe, hyperparams, git sha. Main process only, mirroring _save_outputs.
    if trainer.accelerator.is_main_process:
        prefix = os.environ.get("S3_PREFIX", "v2")
        meta_path = write_run_meta(
            args.output_dir,
            family=args.family,
            stage="sft",
            run_id=args.run_id or Path(args.output_dir).name,
            base_ref={"path": f"{prefix}/models/{args.family}/base", "md5": None},
            dataset={"path": f"{prefix}/sft/{args.family}/train.jsonl",
                     "md5": md5_file(data_path)},
            # LoRA on a bf16 base (load_base_model), NOT qlora: serve-time fidelity must
            # match the training-time base dtype (v1 "serve merged bf16" finding). A future
            # 4-bit training path would set method="qlora"/quant_type="nf4" here instead.
            quant={"method": "lora", "quant_type": None, "compute_dtype": "bfloat16"},
            hyperparams={
                "lora_r": args.lora_r,
                "lora_alpha": args.lora_alpha,
                "lora_dropout": args.lora_dropout,
                "lr": args.learning_rate,
                "epochs": args.num_train_epochs,
                "max_length": args.max_length,
                "per_device_train_batch_size": args.per_device_train_batch_size,
                "gradient_accumulation_steps": args.gradient_accumulation_steps,
                "seed": args.seed,
            },
            git_cwd=ROOT,
        )
        print(f"Saved run meta -> {meta_path}")


def _print_masked_example(tokenizer, ds) -> None:
    if len(ds) == 0:
        print("\n[dry-run] no examples survived filtering -- nothing to show.")
        return
    ex = ds[0]
    ids, labels = ex["input_ids"], ex["labels"]
    trained = [ids[t] for t in range(len(ids)) if labels[t] != -100]
    masked = [ids[t] for t in range(len(ids)) if labels[t] == -100]
    n_tr = len(trained)
    print("\n=== one rendered+masked example (row 0) ===")
    print(f"  total tokens: {len(ids)}   trained(loss): {n_tr} ({100*n_tr/len(ids):.1f}%)   "
          f"masked: {len(masked)}")
    print("  --- TRAINED (loss) tokens, decoded ---")
    print("   ", repr(tokenizer.decode(trained, skip_special_tokens=False)[:600]))
    print("  --- MASKED (-100) prefix, decoded ---")
    print("   ", repr(tokenizer.decode(masked, skip_special_tokens=False)[:300]), "...")


def _save_outputs(trainer, tokenizer, output_dir: str, attn: str) -> None:
    """Save the LoRA adapter AND a merged bf16 full checkpoint (+ tokenizer).

    The merged dir is a plain HF model so eval (scripts/eval_split.py --model gemma
    --model-path <dir>/merged) loads it with no peft dependency.
    """
    adapter_dir = os.path.join(output_dir, "adapter")
    merged_dir = os.path.join(output_dir, "merged")

    # Adapter: Trainer handles main-process-only saving under DDP.
    trainer.save_model(adapter_dir)
    if trainer.accelerator.is_main_process:
        tokenizer.save_pretrained(adapter_dir)

    trainer.accelerator.wait_for_everyone()
    if trainer.accelerator.is_main_process:
        import torch
        from peft import PeftModel
        from transformers import AutoModelForCausalLM
        from model import MODEL_ID, _force_repeat_kv_for_efficient_sdpa
        if attn == "sdpa":
            _force_repeat_kv_for_efficient_sdpa()
        print(f"Merging adapter -> bf16 full checkpoint at {merged_dir} ...", flush=True)
        base = AutoModelForCausalLM.from_pretrained(
            MODEL_ID, dtype=torch.bfloat16, attn_implementation=attn)
        merged = PeftModel.from_pretrained(base, adapter_dir).merge_and_unload()
        merged.save_pretrained(merged_dir, safe_serialization=True)
        tokenizer.save_pretrained(merged_dir)
        print(f"Saved adapter -> {adapter_dir}\nSaved merged model -> {merged_dir}")


if __name__ == "__main__":
    main()
